apiVersion: v1
kind: Service
metadata:
  name: parfume-service
  namespace: parfume
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31000
  selector:
    app: parfume-app
